'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ne';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'app.name': 'POSHAN SAATHI',
    'app.tagline': 'Your Intelligent Nutrition Companion',
    'app.companion': 'AI Companion',
    'nav.chat': 'AI Chat Companion',
    'nav.theme': 'Toggle Theme',
    'nav.edit': 'Edit Profile',
    'nav.logout': 'Logout',
    'hero.namaste': 'NAMASTE',
    'hero.subtitle': 'Your Intelligent Nutrition',
    'hero.companion': 'Companion',
    'hero.ready': 'Is Ready.',
    'dashboard.explore': 'Explore Module',
    'chat.new': 'New Chat',
    'chat.clear': 'Clear History',
    'chat.placeholder': 'Ask Poshan Saathi anything...',
    'chat.disclaimer': 'AI-generated advice. Consult a professional for critical health decisions.',
    'chat.history': 'Recent Chats',
    'module.analysis': 'Analysis Module',
    'module.back': 'Back',
    'module.submit': 'Analyze Now',
    'module.loading': 'Analyzing...',
    'profile.title': 'Your Health Profile',
    'profile.save': 'Save Profile',
    'profile.name': 'Full Name',
    'profile.age': 'Age',
    'profile.sex': 'Sex',
    'profile.weight': 'Weight (kg)',
    'profile.location': 'Location',
    'profile.pregnancy': 'Pregnancy/Breastfeeding Status',
    'profile.disease': 'Disease History',
    'profile.diet': 'Diet Type',
    'profile.budget': 'Monthly Food Budget (NPR)',
    'profile.symptoms': 'Current Symptoms',
    'module.deficiency.title': 'Nutrition Deficiency Profiling',
    'module.deficiency.description': 'Analyze symptoms for hidden micronutrient gaps (Iron, Vit A, Iodine, Zinc).',
    'module.meal-planner.title': 'Smart Meal Planner',
    'module.meal-planner.description': 'Personalized weekly meal plans within your budget and local availability.',
    'module.food-lookup.title': 'Healthy Food Lookup',
    'module.food-lookup.description': 'Search foods for macro breakdown, sodium levels, and healthier alternatives.',
    'module.absorption.title': 'Absorption Advisor',
    'module.absorption.description': 'Analyze meals for nutrient inhibitors and get simple fixes (e.g. lemon + spinach).',
    'module.superfoods.title': 'Hidden Superfoods',
    'module.superfoods.description': 'Rediscover indigenous Nepali foods like sisnu and kinema for better health.',
    'module.budget-meals.title': 'Healthy Budget Meals',
    'module.budget-meals.description': 'Find quantified alternatives showing better health value per rupee spent.',
    'module.plate-recognition.title': 'Plate Recognition',
    'module.plate-recognition.description': 'Snap your plate to identify foods, estimate portions, and calculate macros.',
    'module.seasonal.title': 'Seasonal Calendar',
    'module.seasonal.description': 'Track seasonal foods and adjust diet plans to predict the hungry season.',
    'module.recipes.title': 'Nepali Recipes',
    'module.recipes.description': 'Enter ingredients from your kitchen to get healthy, traditional Nepali recipe suggestions.',
    'module.nutri-score.title': 'Poshan Score',
    'module.nutri-score.description': 'Scan a barcode or snap a picture of a nutrition label to get its Poshan Score (A-E) and healthier alternatives.',
    'onboarding.edit': 'Edit Profile',
    'onboarding.update': 'Update your details',
    'onboarding.google': 'Continue with Google',
    'onboarding.authenticated': 'Authenticated',
    'onboarding.success.title': 'Profile Updated',
    'onboarding.success.desc': 'Your information has been saved successfully.',
    'onboarding.step': 'Step',
    'onboarding.of': 'of',
    'onboarding.next': 'Next',
    'onboarding.back': 'Back',
    'onboarding.complete': 'Complete',
    'onboarding.save': 'Save Profile',
    'onboarding.basic.title': 'Basic Information',
    'onboarding.basic.desc': "Let's start with the basics to personalize your experience.",
    'onboarding.health.title': 'Health & Lifestyle',
    'onboarding.health.desc': 'Help us understand your current health status.',
    'onboarding.diet.title': 'Dietary Habits',
    'onboarding.diet.desc': 'Tell us about your everyday eating patterns.',
    'onboarding.socio.title': 'Socioeconomic Factors',
    'onboarding.socio.desc': 'This helps us recommend appropriate and affordable meal plans.',
    'onboarding.name.label': 'Full Name *',
    'onboarding.name.placeholder': 'e.g. Ram Bahadur',
    'onboarding.age.label': 'Age *',
    'onboarding.age.placeholder': '35',
    'onboarding.sex.label': 'Sex *',
    'onboarding.sex.select': 'Select Sex',
    'onboarding.sex.male': 'Male',
    'onboarding.sex.female': 'Female',
    'onboarding.sex.other': 'Other',
    'onboarding.weight.label': 'Weight (kg) *',
    'onboarding.weight.placeholder': '65',
    'onboarding.location.label': 'Location (District) *',
    'onboarding.location.select': 'Select a District',
    'onboarding.pregnancy.label': 'Pregnancy / Breastfeeding Status',
    'onboarding.pregnancy.select': 'Select Status',
    'onboarding.pregnancy.na': 'Not Applicable',
    'onboarding.pregnancy.pregnant': 'Pregnant',
    'onboarding.pregnancy.breastfeeding': 'Breastfeeding',
    'onboarding.disease.label': 'History of Disease',
    'onboarding.disease.placeholder': 'None',
    'onboarding.substance.label': 'Substance Abuse',
    'onboarding.substance.alcohol': 'Alcohol',
    'onboarding.substance.smoking': 'Smoking',
    'onboarding.substance.tobacco': 'Tobacco',
    'onboarding.symptoms.label': 'Current Health Symptoms *',
    'onboarding.symptoms.placeholder': 'e.g., fatigue, gum bleeding, hair loss, pale skin...',
    'onboarding.symptoms.desc': 'This helps us profile potential micronutrient deficiencies.',
    'onboarding.dietType.label': 'Diet Type *',
    'onboarding.dietType.select': 'Select Diet Type',
    'onboarding.dietType.veg': 'Vegetarian',
    'onboarding.dietType.nonveg': 'Non-Vegetarian',
    'onboarding.dietType.vegan': 'Vegan',
    'onboarding.frequency.label': 'Meat/Fish/Eggs Frequency *',
    'onboarding.frequency.select': 'Select Frequency',
    'onboarding.frequency.daily': 'Daily',
    'onboarding.frequency.few': 'Few times a week',
    'onboarding.frequency.once': 'Once a week',
    'onboarding.frequency.rarely': 'Rarely',
    'onboarding.frequency.never': 'Never',
    'onboarding.utensil.label': 'Primary Cooking Utensil *',
    'onboarding.utensil.select': 'Select Utensil',
    'onboarding.utensil.aluminum': 'Aluminum',
    'onboarding.utensil.iron': 'Iron (Cast Iron)',
    'onboarding.utensil.clay': 'Clay Pot',
    'onboarding.utensil.steel': 'Stainless Steel',
    'onboarding.utensil.nonstick': 'Non-stick',
    'onboarding.utensil.desc': 'Iron pots can increase dietary iron intake.',
    'onboarding.budget.label': 'Household Food Budget (Monthly in NPR) *',
    'onboarding.budget.placeholder': 'e.g., 15000',
    'onboarding.familySize.label': 'Household Size (Number of people) *',
    'onboarding.familySize.placeholder': 'e.g., 4',
    'onboarding.income.label': 'Household Income Level *',
    'onboarding.income.select': 'Select Income Level',
    'onboarding.income.low': 'Low Income',
    'onboarding.income.middle': 'Middle Income',
    'onboarding.income.high': 'High Income',
    'onboarding.error.name': 'Name is required',
    'onboarding.error.age': 'Please enter a valid age (1-150)',
    'onboarding.error.weight': 'Please enter a valid weight',
    'onboarding.error.location': 'Please select a valid district',
    'onboarding.error.sex': 'Sex is required',
    'onboarding.error.symptoms': 'Please describe your symptoms',
    'onboarding.error.dietType': 'Diet type is required',
    'onboarding.error.dietFrequency': 'Diet frequency is required',
    'onboarding.error.cookingUtensil': 'Cooking utensil is required',
    'onboarding.error.budget': 'Please enter a valid budget',
    'onboarding.error.familySize': 'Please enter a valid household size (minimum 1)',
    'onboarding.error.income': 'Income level is required',
    'toast.online': 'You are back online! Syncing data...',
    'toast.offline': 'You are offline. Changes will be saved locally.',
    'toast.synced': 'Your profile has been synced to the cloud!',
    'toast.login.success': 'Successfully logged in!',
    'toast.logout.success': 'Successfully logged out!',
    'toast.profile.updated': 'Profile updated!',
    'toast.profile.saved': 'Profile saved locally!',
    'toast.offline.saved': 'Changes saved locally. They will sync when you are back online.',
    'toast.sync.error': 'Could not sync profile to cloud. Changes kept locally.',
    'offline.message': 'No internet connection. Operating offline.',
  },
  ne: {
    'app.name': 'पोषण साथी',
    'app.tagline': 'तपाईंको स्मार्ट पोषण साथी',
    'app.companion': 'एआई साथी',
    'nav.chat': 'च्याट साथी',
    'nav.theme': 'थिम परिवर्तन',
    'nav.edit': 'प्रोफाइल सच्याउनुहोस्',
    'nav.logout': 'लगआउट गर्नुहोस्',
    'hero.namaste': 'नमस्ते',
    'hero.subtitle': 'तपाईंको व्यक्तिगत पोषण',
    'hero.companion': 'साथी',
    'hero.ready': 'सेवामा हाजिर छ।',
    'dashboard.explore': 'सुविधाहरू खोज्नुहोस्',
    'chat.new': 'नयाँ कुराकानी',
    'chat.clear': 'कुराकानी मेटाउनुहोस्',
    'chat.placeholder': 'पोषण साथीलाई केही सोध्नुहोस्...',
    'chat.disclaimer': 'यो एआईले दिएको सुझाव हो। गम्भीर स्वास्थ्य समस्याको लागि डाक्टरको सल्लाह लिनुहोला।',
    'chat.history': 'अघिल्ला कुराकानीहरू',
    'module.analysis': 'विश्लेषण',
    'module.back': 'पछाडि',
    'module.submit': 'विश्लेषण गर्नुहोस्',
    'module.loading': 'विश्लेषण गर्दै...',
    'profile.title': 'तपाईंको स्वास्थ्य विवरण',
    'profile.save': 'विवरण सुरक्षित गर्नुहोस्',
    'profile.name': 'पूरा नाम',
    'profile.age': 'उमेर',
    'profile.sex': 'लिङ्ग',
    'profile.weight': 'तौल (कि.ग्रा.)',
    'profile.location': 'जिल्ला',
    'profile.pregnancy': 'गर्भवती/स्तनपान अवस्था',
    'profile.disease': 'दीर्घकालीन रोगहरू',
    'profile.diet': 'खानपानको प्रकार',
    'profile.budget': 'मासिक खाना खर्च (रु.)',
    'profile.symptoms': 'हालका स्वास्थ्य समस्याहरू',
    'module.deficiency.title': 'पोषण अभावको पहिचान',
    'module.deficiency.description': 'तपाईंका लक्षणहरूका आधारमा भिटामिन र खनिजको कमी पत्ता लगाउनुहोस्।',
    'module.meal-planner.title': 'स्मार्ट भोजन योजना',
    'module.meal-planner.description': 'तपाईंको बजेट र स्थानीय खानेकुरा अनुसारको साप्ताहिक भोजन योजना।',
    'module.food-lookup.title': 'स्वस्थ खानाको जानकारी',
    'module.food-lookup.description': 'खानाको पौष्टिक तत्व र स्वस्थ विकल्पहरू खोज्नुहोस्।',
    'module.absorption.title': 'पोषण अवशोषण सल्लाह',
    'module.absorption.description': 'खानाबाट अधिकतम पोषण प्राप्त गर्ने सरल तरिकाहरू।',
    'module.superfoods.title': 'स्थानीय सुपरफुड',
    'module.superfoods.description': 'सिस्नु र किनेमा जस्ता रैथाने नेपाली खानाका फाइदा जान्नुहोस्।',
    'module.budget-meals.title': 'सस्तो र स्वस्थ भोजन',
    'module.budget-meals.description': 'कम खर्चमा धेरै पोषण दिने खानाका विकल्पहरू फेला पार्नुहोस्।',
    'module.plate-recognition.title': 'खाना चिन्ने प्रविधि',
    'module.plate-recognition.description': 'फोटो खिचेर खानाको पौष्टिक तत्व र मात्रा थाहा पाउनुहोस्।',
    'module.seasonal.title': 'मौसमी खानेकुरा',
    'module.seasonal.description': 'मौसम अनुसार पाइने खानेकुराको जानकारी र आहार योजना।',
    'module.recipes.title': 'नेपाली परिकार',
    'module.recipes.description': 'भान्सामा भएका सामग्रीबाट स्वस्थ र परम्परागत नेपाली परिकार बनाउन सिक्नुहोस्।',
    'module.nutri-score.title': 'पोषण स्कोर',
    'module.nutri-score.description': 'प्याकेटको खाना स्क्यान गरी त्यसको पोषण स्तर र स्वस्थ विकल्प थाहा पाउनुहोस्।',
    'onboarding.edit': 'विवरण सच्याउनुहोस्',
    'onboarding.update': 'आफ्नो विवरण अद्यावधिक गर्नुहोस्',
    'onboarding.google': 'Google बाट लगइन गर्नुहोस्',
    'onboarding.authenticated': 'प्रमाणित भयो',
    'onboarding.success.title': 'विवरण सुरक्षित भयो',
    'onboarding.success.desc': 'तपाईंको जानकारी सफलतापूर्वक सुरक्षित भयो।',
    'onboarding.step': 'चरण',
    'onboarding.of': '/',
    'onboarding.next': 'अर्को',
    'onboarding.back': 'अघिल्लो',
    'onboarding.complete': 'सम्पन्न गर्नुहोस्',
    'onboarding.save': 'विवरण सुरक्षित गर्नुहोस्',
    'onboarding.basic.title': 'आधारभूत जानकारी',
    'onboarding.basic.desc': 'तपाईंलाई सुहाउँदो सल्लाह दिन कृपया आफ्ना विवरणहरू भर्नुहोस्।',
    'onboarding.health.title': 'स्वास्थ्य र जीवनशैली',
    'onboarding.health.desc': 'तपाईंको अहिलेको स्वास्थ्य अवस्था बुझ्न हामीलाई मद्दत गर्नुहोस्।',
    'onboarding.diet.title': 'खानपानको बानी',
    'onboarding.diet.desc': 'तपाईंको दैनिक खानपानको बानीबारे हामीलाई बताउनुहोस्।',
    'onboarding.socio.title': 'आर्थिक अवस्था',
    'onboarding.socio.desc': 'यसले तपाईंको बजेट अनुसारको सही खाना सिफारिस गर्न मद्दत गर्नेछ।',
    'onboarding.name.label': 'पूरा नाम *',
    'onboarding.name.placeholder': 'जस्तै: राम बहादुर',
    'onboarding.age.label': 'उमेर *',
    'onboarding.age.placeholder': '३५',
    'onboarding.sex.label': 'लिङ्ग *',
    'onboarding.sex.select': 'लिङ्ग छान्नुहोस्',
    'onboarding.sex.male': 'पुरुष',
    'onboarding.sex.female': 'महिला',
    'onboarding.sex.other': 'अन्य',
    'onboarding.weight.label': 'तौल (कि.ग्रा.) *',
    'onboarding.weight.placeholder': '६५',
    'onboarding.location.label': 'जिल्ला *',
    'onboarding.location.select': 'जिल्ला छान्नुहोस्',
    'onboarding.pregnancy.label': 'गर्भावस्था / स्तनपान अवस्था',
    'onboarding.pregnancy.select': 'अवस्था छान्नुहोस्',
    'onboarding.pregnancy.na': 'लागू हुँदैन',
    'onboarding.pregnancy.pregnant': 'गर्भवती',
    'onboarding.pregnancy.breastfeeding': 'स्तनपान गराउने आमा',
    'onboarding.disease.label': 'दीर्घकालीन रोगहरू',
    'onboarding.disease.placeholder': 'छैन',
    'onboarding.substance.label': 'लागू पदार्थ / मदिरा सेवन',
    'onboarding.substance.alcohol': 'मदिरा',
    'onboarding.substance.smoking': 'धुम्रपान',
    'onboarding.substance.tobacco': 'सुर्तीजन्य पदार्थ',
    'onboarding.symptoms.label': 'हाल देखिएका स्वास्थ्य समस्या वा लक्षणहरू *',
    'onboarding.symptoms.placeholder': 'जस्तै: थकान, कपाल झर्ने, रिङ्गटा लाग्ने...',
    'onboarding.symptoms.desc': 'यसले तपाईंको शरीरमा कुन भिटामिन वा खनिजको कमी छ भनेर पत्ता लगाउन मद्दत गर्छ।',
    'onboarding.dietType.label': 'खानपानको प्रकार *',
    'onboarding.dietType.select': 'खानपानको प्रकार छान्नुहोस्',
    'onboarding.dietType.veg': 'शाकाहारी',
    'onboarding.dietType.nonveg': 'मांसाहारी',
    'onboarding.dietType.vegan': 'भेगन (पूर्ण शाकाहारी)',
    'onboarding.frequency.label': 'मासु/माछा/अण्डा कति पटक खानुहुन्छ? *',
    'onboarding.frequency.select': 'छान्नुहोस्',
    'onboarding.frequency.daily': 'हरेक दिन',
    'onboarding.frequency.few': 'हप्तामा केही पटक',
    'onboarding.frequency.once': 'हप्तामा एक पटक',
    'onboarding.frequency.rarely': 'कहिलेकाहीँ',
    'onboarding.frequency.never': 'खाँदिन',
    'onboarding.utensil.label': 'खाना पकाउन प्रयोग हुने मुख्य भाँडो *',
    'onboarding.utensil.select': 'भाँडो छान्नुहोस्',
    'onboarding.utensil.aluminum': 'आल्मुनियम',
    'onboarding.utensil.iron': 'फलामको भाँडो',
    'onboarding.utensil.clay': 'माटोको भाँडो',
    'onboarding.utensil.steel': 'स्टिलको भाँडो',
    'onboarding.utensil.nonstick': 'नन-स्टिक (नटाँसिने)',
    'onboarding.utensil.desc': 'फलामको भाँडामा पकाउँदा खानामा आइरनको मात्रा बढ्छ।',
    'onboarding.budget.label': 'मासिक खाना खर्च (रु.) *',
    'onboarding.budget.placeholder': 'जस्तै: १५०००',
    'onboarding.familySize.label': 'परिवारको सदस्य संख्या *',
    'onboarding.familySize.placeholder': 'जस्तै: ४',
    'onboarding.income.label': 'पारिवारिक आय स्तर *',
    'onboarding.income.select': 'आय स्तर छान्नुहोस्',
    'onboarding.income.low': 'न्यून आय',
    'onboarding.income.middle': 'मध्यम आय',
    'onboarding.income.high': 'उच्च आय',
    'onboarding.error.name': 'नाम अनिवार्य छ',
    'onboarding.error.age': 'कृपया सही उमेर राख्नुहोस्',
    'onboarding.error.weight': 'कृपया सही तौल राख्नुहोस्',
    'onboarding.error.location': 'कृपया जिल्ला छान्नुहोस्',
    'onboarding.error.sex': 'लिङ्ग अनिवार्य छ',
    'onboarding.error.symptoms': 'कृपया आफ्ना लक्षणहरू लेख्नुहोस्',
    'onboarding.error.dietType': 'खानपानको प्रकार अनिवार्य छ',
    'onboarding.error.dietFrequency': 'कृपया कति पटक खानुहुन्छ छान्नुहोस्',
    'onboarding.error.cookingUtensil': 'कृपया पकाउने भाँडो छान्नुहोस्',
    'onboarding.error.budget': 'कृपया सही बजेट राख्नुहोस्',
    'onboarding.error.familySize': 'कृपया सही सदस्य संख्या राख्नुहोस् (कम्तिमा १)',
    'onboarding.error.income': 'आय स्तर अनिवार्य छ',
    'toast.online': 'इन्टरनेट जडान भयो! डाटा सुरक्षित हुँदैछ...',
    'toast.offline': 'इन्टरनेट जडान छैन। विवरणहरू डिभाइसमै सुरक्षित हुनेछन्।',
    'toast.synced': 'तपाईंको विवरण सुरक्षित भयो!',
    'toast.login.success': 'लगइन सफल भयो!',
    'toast.logout.success': 'लगआउट सफल भयो!',
    'toast.profile.updated': 'विवरण अद्यावधिक भयो!',
    'toast.profile.saved': 'विवरण डिभाइसमै सुरक्षित भयो!',
    'toast.offline.saved': 'परिवर्तनहरू डिभाइसमै सेभ भएका छन्। इन्टरनेट आएपछि सिंक हुनेछन्।',
    'toast.sync.error': 'क्लाउडमा सेभ गर्न सकिएन। परिवर्तनहरू डिभाइसमै सुरक्षित छन्।',
    'offline.message': 'इन्टरनेट जडान छैन। अफलाइन मोडमा चल्दैछ।'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      const savedLang = localStorage.getItem('poshan_saathi_lang') as Language;
      if (savedLang && ['en', 'ne'].includes(savedLang)) {
        return savedLang;
      }
    }
    return 'en';
  });

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('poshan_saathi_lang', lang);
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
