export type FoodItem = {
  name: string;
  localName?: string;
  phonetic?: string;
  category: 'Staple' | 'Vegetable' | 'Protein' | 'Fruit' | 'Snack' | 'Dairy' | 'Indigenous';
  calories: number; // per 100g or standard serving
  protein: number; // g
  carbs: number; // g
  fat: number; // g
  iron: number; // mg
  vitaminA?: number; // mcg
  zinc?: number; // mg
  sodium?: number; // mg
  price: number; // Estimated NPR (Restaurant/Eatery price for meals, Retail MRP for packaged snacks, per serving/packet)
  description: string;
  preparation?: string; // Common preparation method
  benefits: string;
};

export const nepaliFoodDatabase: FoodItem[] = [
  {
    name: 'Amaranth Seed',
    localName: 'Latteko Dana',
    phonetic: 'Lah-tay-ko Dah-nah',
    category: 'Staple',
    calories: 375,
    protein: 9.4,
    carbs: 68.1,
    fat: 7.17,
    iron: 5.2,
    zinc: 0,
    price: 150,
    description: 'Highly nutritious pseudo-cereal, rich in minerals.',
    preparation: 'Can be popped like popcorn, boiled into porridge, or ground into flour for flatbreads.',
    benefits: 'Excellent source of iron and phosphorus. Gluten-free.'
  },
  {
    name: 'Buckwheat (Whole)',
    localName: 'Phapar',
    phonetic: 'Phaa-par',
    category: 'Staple',
    calories: 323,
    protein: 10.3,
    carbs: 65.1,
    fat: 2.4,
    iron: 15.5,
    zinc: 0,
    price: 120,
    description: 'A nutrient-dense pseudo-cereal common in mountain regions.',
    preparation: 'Ground into flour to make Dhindo or flatbreads (Roti).',
    benefits: 'Exceptionally high in iron (15.5mg/100g) and fiber. High in rutin for heart health.'
  },
  {
    name: 'Foxtail Millet',
    localName: 'Kaguno',
    phonetic: 'Kah-goo-no',
    category: 'Staple',
    calories: 331,
    protein: 12.3,
    carbs: 60.9,
    fat: 4.3,
    iron: 12.9,
    price: 130,
    description: 'An underutilized, highly nutritious millet grown in the Karnali region.',
    preparation: 'Boiled and eaten like rice, or cooked into a sweet or savory porridge (Kheer).',
    benefits: 'Rich in protein, fiber, and iron (12.9mg/100g). Excellent for diabetic diets.'
  },
  {
    name: 'Horse Gram (Black)',
    localName: 'Gahat',
    phonetic: 'Ga-hat',
    category: 'Protein',
    calories: 321,
    protein: 22,
    carbs: 57.2,
    fat: 0.5,
    iron: 6.77,
    price: 120,
    description: 'A highly nutritious, warming legume consumed mostly in winter.',
    preparation: 'Soaked overnight and slow-cooked into a thick, dark soup. Often tempered with garlic and jimbu.',
    benefits: 'High in protein and iron. Traditionally believed to help dissolve kidney stones.'
  },
  {
    name: 'Black Gram (Dal)',
    localName: 'Masko Dal',
    phonetic: 'Maas-ko Daal',
    category: 'Protein',
    calories: 347,
    protein: 24,
    carbs: 59.6,
    fat: 1.4,
    iron: 3.8,
    price: 160,
    description: 'A staple lentil in Nepal, often used to make thick, flavorful dal.',
    preparation: 'Boiled with spices and tempered with ghee and jimbu.',
    benefits: 'Very high in protein (24g/100g) and a good source of iron.'
  },
  {
    name: 'Soyabean (Black)',
    localName: 'Bhatamas, Kalo',
    phonetic: 'Bha-ta-maas, Kaa-lo',
    category: 'Protein',
    calories: 393,
    protein: 33.3,
    carbs: 31.3,
    fat: 15,
    iron: 9.5,
    price: 140,
    description: 'Black soybeans, often roasted as a snack or used in traditional dishes.',
    preparation: 'Roasted and mixed with spices (Bhatmas Sadeko) or fermented into Kinema.',
    benefits: 'Exceptionally high in protein (33.3g/100g) and iron (9.5mg/100g).'
  },
  {
    name: 'Mustard Leaves',
    localName: 'Rayoko Sag',
    phonetic: 'Raa-yo-ko Saag',
    category: 'Vegetable',
    calories: 34,
    protein: 4,
    carbs: 3.2,
    fat: 0.6,
    iron: 16.3,
    vitaminA: 2622,
    price: 40,
    description: 'A very common, slightly bitter leafy green vegetable in Nepal.',
    preparation: 'Stir-fried lightly with mustard oil, dry chilies, and garlic.',
    benefits: 'Incredible source of iron (16.3mg/100g) and Vitamin A (Carotene).'
  },
  {
    name: 'Spinach',
    localName: 'Palungko Sag',
    phonetic: 'Paa-lung-ko Saag',
    category: 'Vegetable',
    calories: 26,
    protein: 2,
    carbs: 2.9,
    fat: 0.7,
    iron: 1.14,
    vitaminA: 3049,
    price: 50,
    description: 'Tender leafy greens, widely available in winter.',
    preparation: 'Lightly wilted or cooked into a curry with potatoes.',
    benefits: 'Very high in Vitamin A (Carotene) and a good source of dietary fiber.'
  },
  {
    name: 'Dal Bhat',
    localName: 'दाल भात',
    phonetic: 'Daal Bhaat',
    category: 'Staple',
    calories: 345,
    protein: 6.8,
    carbs: 78.2,
    fat: 0.5,
    iron: 0.7,
    zinc: 2.1,
    price: 250,
    description: 'The national dish of Nepal, consisting of lentil soup (dal) and boiled rice (bhat).',
    preparation: 'Boil white or brown rice. Cook lentils (masuro/rahar) with turmeric and salt, then temper with ghee, cumin, and garlic.',
    benefits: 'Complete protein when combined. High in fiber and complex carbohydrates.'
  },
  {
    name: 'Dhindo',
    localName: 'ढिँडो',
    phonetic: 'Dheen-do',
    category: 'Staple',
    calories: 360,
    protein: 9.2,
    carbs: 72.1,
    fat: 3.9,
    iron: 2.4,
    zinc: 2.5,
    price: 300,
    description: 'Traditional thick porridge made from maize, buckwheat, or millet flour.',
    preparation: 'Gradually pour flour into boiling water while stirring continuously with a wooden spatula (Dabilo) until thick and cooked.',
    benefits: 'Gluten-free, high in iron and magnesium. Low glycemic index.'
  },
  {
    name: 'Gundruk',
    localName: 'गुन्द्रुक',
    phonetic: 'Goon-drook',
    category: 'Indigenous',
    calories: 297,
    protein: 27,
    carbs: 40.7,
    fat: 2.9,
    iron: 50,
    price: 100,
    description: 'Fermented and sun-dried leafy green vegetable (mustard, radish, or cauliflower leaves).',
    preparation: 'Wilt leaves, crush, pack tightly in an earthen pot to ferment for a week, then sun-dry. Often cooked as a sour soup with soybeans.',
    benefits: 'Excellent source of probiotics and minerals. Exceptionally high in iron and calcium.'
  },
  {
    name: 'Stinging Nettle',
    localName: 'सिस्नु',
    phonetic: 'Sis-noo',
    category: 'Indigenous',
    calories: 53,
    protein: 6.9,
    carbs: 5,
    fat: 0.2,
    iron: 5.5,
    price: 150,
    description: 'Stinging nettle soup, a traditional Himalayan superfood.',
    preparation: 'Pluck fresh nettle leaves with tongs, boil in water to remove the sting, and thicken with a handful of maize or wheat flour.',
    benefits: 'Extremely high in iron, calcium, and Vitamin A. Good for anemia and joint pain.'
  },
  {
    name: 'Kinema',
    localName: 'किनेमा',
    phonetic: 'Kee-nay-maa',
    category: 'Indigenous',
    calories: 432,
    protein: 43.2,
    carbs: 20.9,
    fat: 19.5,
    iron: 10.4,
    zinc: 3.0,
    price: 100,
    description: 'Fermented soybean product common in eastern Nepal (Limbu/Rai communities).',
    preparation: 'Boil soybeans, wrap in fern leaves, and leave in a warm place to ferment until sticky and pungent. Cooked as a savory curry.',
    benefits: 'High in protein and B-vitamins. Probiotic benefits.'
  },
  {
    name: 'Sel Roti',
    localName: 'सेल रोटी',
    phonetic: 'Sel Ro-tee',
    category: 'Snack',
    calories: 225,
    protein: 4.5,
    carbs: 61.3,
    fat: 11.7,
    iron: 1.2,
    price: 35,
    description: 'Traditional ring-shaped sweet fried rice bread, essential during Tihar.',
    preparation: 'Make a semi-liquid batter of soaked rice flour, sugar, ghee, and cardamom. Deep fry in hot oil in a ring shape.',
    benefits: 'Energy-dense, culturally significant.'
  },
  {
    name: 'Momo (Buff)',
    localName: 'ममो',
    phonetic: 'Mo-mo',
    category: 'Snack',
    calories: 215,
    protein: 11.7,
    carbs: 24.6,
    fat: 7.7,
    iron: 1.8,
    price: 180,
    description: 'Nepali-style dumplings filled with minced buffalo meat and spices.',
    preparation: 'Wrap minced meat mixed with onions, ginger, and garlic in small wheat flour dough circles. Steam for 10-15 minutes.',
    benefits: 'Balanced meal if served with tomato achar (rich in Vit C).'
  },
  {
    name: 'Kwanti',
    localName: 'क्वाटी',
    phonetic: 'Kwaa-tee',
    category: 'Protein',
    calories: 346,
    protein: 22.9,
    carbs: 60.6,
    fat: 1.3,
    iron: 5.1,
    zinc: 4.0,
    price: 150,
    description: 'Sprouted mixed bean soup (9 types of beans), traditionally eaten during Janai Purnima.',
    preparation: 'Soak 9 varieties of beans for 2-3 days until sprouted. Slow-cook into a thick soup and temper with ajwain (jwano).',
    benefits: 'Very high in protein and minerals. Sprouting increases nutrient bioavailability.'
  },
  {
    name: 'Millet (Kodo)',
    localName: 'कोदो',
    phonetic: 'Ko-do',
    category: 'Staple',
    calories: 328,
    protein: 7.3,
    carbs: 72,
    fat: 1.3,
    iron: 3.9,
    zinc: 2.7,
    price: 100,
    description: 'Small-seeded grass, a staple in many hilly regions of Nepal.',
    preparation: 'Ground into flour for Dhindo or Roti, or fermented to make the traditional alcoholic beverage Tongba.',
    benefits: 'High in calcium and antioxidants. Drought-resistant crop.'
  },
  {
    name: 'Chino (Proso Millet)',
    localName: 'चिनो',
    phonetic: 'Chee-no',
    category: 'Staple',
    calories: 366,
    protein: 10.5,
    carbs: 65.9,
    fat: 6.7,
    iron: 11.0,
    price: 130,
    description: 'A traditional staple millet from the high mountains of Mid and Far-Western Nepal.',
    preparation: 'Cooked similarly to rice or ground into flour for flatbreads.',
    benefits: 'Very high in iron and energy. Essential for food security in arid regions.'
  },
  {
    name: 'Bara',
    localName: 'बारा',
    phonetic: 'Baa-raa',
    category: 'Snack',
    calories: 344,
    protein: 21,
    carbs: 58.8,
    fat: 1.6,
    iron: 8.4,
    price: 80,
    description: 'A savory Newari lentil pancake made from black gram (Maas).',
    preparation: 'Soak black gram overnight, remove skins, grind into a thick paste with ginger/garlic, and pan-fry like a thick pancake.',
    benefits: 'Excellent source of plant-based protein and iron.'
  },
  {
    name: 'Yomari',
    localName: 'योमरी',
    phonetic: 'Yo-ma-ree',
    category: 'Snack',
    calories: 350,
    protein: 6,
    carbs: 75,
    fat: 2,
    iron: 2.0,
    price: 60,
    description: 'A Newari steamed dumpling with an external covering of rice flour and a sweet filling.',
    preparation: 'Knead rice flour with hot water. Shape into a pointed fig, fill with Chaku (molasses) and sesame seeds, and steam.',
    benefits: 'Provides quick energy and warmth during the winter harvest festival (Yomari Punhi).'
  },
  {
    name: 'Lapsi',
    localName: 'लप्सी',
    phonetic: 'Lap-see',
    category: 'Fruit',
    calories: 73,
    protein: 0.5,
    carbs: 17.6,
    fat: 0.5,
    iron: 2.7,
    vitaminA: 50,
    price: 50,
    description: 'Nepali hog plum, unique to Nepal.',
    preparation: 'Boiled to remove the skin and seeds, then cooked with sugar, salt, and spices to make candy (Mada) or pickles.',
    benefits: 'Very high in Vitamin C, which aids iron absorption.'
  },
  {
    name: 'Chauri Gai Milk',
    localName: 'चौरीको दूध',
    phonetic: 'Chau-ree-ko Doodh',
    category: 'Dairy',
    calories: 105,
    protein: 4.3,
    carbs: 7.4,
    fat: 6.5,
    iron: 0.2,
    price: 150,
    description: 'Milk from Yak-Cow hybrids (Chauri) in the Himalayas.',
    preparation: 'Boiled and consumed plain, or churned to make butter and Chhurpi.',
    benefits: 'Higher fat and protein content than regular cow milk. Rich in Omega-3.'
  },
  {
    name: 'Wai Wai Noodles',
    localName: 'वाइ वाइ',
    phonetic: 'Wai Wai',
    category: 'Snack',
    calories: 476,
    protein: 7.68,
    carbs: 66.4,
    fat: 20,
    iron: 4.4,
    sodium: 1300,
    price: 20,
    description: 'Popular instant noodles often eaten raw or cooked.',
    preparation: 'Crush and eat raw with the seasoning powder, or boil in water for 2 minutes with vegetables.',
    benefits: 'High in sodium and refined carbs. Low nutritional value. High risk for hypertension if consumed frequently.'
  },
  {
    name: 'Rumpum Noodles',
    localName: 'रम्पम',
    phonetic: 'Rum-pum',
    category: 'Snack',
    calories: 484,
    protein: 6.15,
    carbs: 70,
    fat: 19.9,
    iron: 5.1,
    sodium: 1250,
    price: 20,
    description: 'Another popular brand of instant noodles in Nepal.',
    preparation: 'Eaten raw as a snack or boiled into a noodle soup.',
    benefits: 'High sodium and empty calories. Not recommended for daily consumption.'
  },
  {
    name: 'Preeti Noodles',
    localName: 'प्रिती चाउचाउ',
    phonetic: 'Pree-tee Chau-chau',
    category: 'Snack',
    calories: 458,
    protein: 7.12,
    carbs: 67,
    fat: 17.9,
    iron: 1.4,
    sodium: 1200,
    price: 20,
    description: 'Classic Nepali instant noodle brand.',
    preparation: 'Usually eaten raw straight from the packet as a crunchy snack.',
    benefits: 'High in sodium and refined wheat. Lacks essential micronutrients.'
  },
  {
    name: 'Chatpate',
    localName: 'चटपटे',
    phonetic: 'Chat-pa-tay',
    category: 'Snack',
    calories: 325,
    protein: 7.5,
    carbs: 73.6,
    fat: 0.1,
    iron: 6.6,
    sodium: 800,
    price: 60,
    description: 'Popular street food made with puffed rice, instant noodles, onions, chilies, and spices.',
    preparation: 'Mix puffed rice (Bhuja), crushed instant noodles, boiled potatoes, chopped onions, tomatoes, chili, spices, and lemon juice.',
    benefits: 'High in sodium and potential hygiene risks. Moderate calorie snack.'
  },
  {
    name: 'Chiura',
    localName: 'चिउरा',
    phonetic: 'Chee-oo-raa',
    category: 'Staple',
    calories: 346,
    protein: 6.6,
    carbs: 77.3,
    fat: 1.2,
    iron: 20.0,
    price: 50,
    description: 'Beaten rice, a traditional staple snack often eaten with yogurt or meat.',
    preparation: 'Paddy is soaked, drained, roasted, and pounded flat. Eaten as-is without further cooking, often paired with curries.',
    benefits: 'Easily digestible carbohydrate source. Exceptionally high in iron due to the iron rollers used in processing.'
  },
  {
    name: 'Bhuteko Makai',
    localName: 'भुटेको मकै',
    phonetic: 'Bhoo-tay-ko Ma-kai',
    category: 'Snack',
    calories: 342,
    protein: 11.1,
    carbs: 66.2,
    fat: 3.6,
    iron: 3.3,
    price: 40,
    description: 'Roasted corn, a traditional and healthy rural snack.',
    preparation: 'Dry roast mature, dried corn kernels in a hot iron pan or sand until they pop and become crunchy.',
    benefits: 'High in dietary fiber and complex carbohydrates. Very healthy alternative to packaged snacks.'
  },
  {
    name: 'Chhurpi',
    localName: 'छुर्पी',
    phonetic: 'Chhoor-pee',
    category: 'Snack',
    calories: 348,
    protein: 24.1,
    carbs: 25.1,
    fat: 6.3,
    iron: 2.1,
    price: 25,
    description: 'Traditional hardened cheese consumed widely in the Himalayan regions.',
    preparation: 'Boil buttermilk, separate the solid mass, press it to remove water, cut into small blocks, and smoke-dry over a fire.',
    benefits: 'Extremely high in protein and calcium. Excellent for dental health and long-lasting energy.'
  },
  {
    name: 'Dalmoth',
    localName: 'दालमोठ',
    phonetic: 'Daal-moth',
    category: 'Snack',
    calories: 550,
    protein: 15,
    carbs: 40,
    fat: 38,
    iron: 3.5,
    sodium: 600,
    price: 50,
    description: 'Fried savory snack mixture of lentils, nuts, and spices.',
    preparation: 'Deep fry lentils (masuro) and peanuts, mix with sev (fried chickpea flour noodles) and spices.',
    benefits: 'Good protein from lentils but very high in fat and calories due to deep frying.'
  },
  {
    name: 'Lays Potato Chips',
    localName: 'लेज',
    phonetic: 'Lays',
    category: 'Snack',
    calories: 536,
    protein: 7,
    carbs: 53,
    fat: 35,
    iron: 1.5,
    sodium: 500,
    price: 50,
    description: 'Packaged potato chips.',
    preparation: 'Commercially deep-fried potato slices with added salt and flavors.',
    benefits: 'High in fat and sodium. Low satiety index, leading to overconsumption.'
  },
  {
    name: 'Kurkure',
    localName: 'कुरकुरे',
    phonetic: 'Koor-koo-ray',
    category: 'Snack',
    calories: 550,
    protein: 6,
    carbs: 54,
    fat: 35,
    iron: 1.0,
    sodium: 900,
    price: 50,
    description: 'Spicy corn puff snack very popular among youth.',
    preparation: 'Commercially extruded cornmeal, deep-fried and heavily seasoned.',
    benefits: 'Ultra-processed, high in trans-fats and sodium. Contributes to NCDs.'
  },
  {
    name: 'Chatamari',
    localName: 'चटामरी',
    phonetic: 'Cha-taa-ma-ree',
    category: 'Snack',
    calories: 220,
    protein: 8.5,
    carbs: 35.2,
    fat: 5.1,
    iron: 2.8,
    price: 120,
    description: 'Newari rice flour crepe, often referred to as "Nepali Pizza".',
    preparation: 'Rice flour batter cooked on a flat pan, topped with minced meat, egg, and vegetables.',
    benefits: 'Gluten-free alternative to wheat-based snacks. Good balance of carbs and protein when topped with meat/egg.'
  },
  {
    name: 'Thukpa',
    localName: 'थुक्पा',
    phonetic: 'Thook-paa',
    category: 'Staple',
    calories: 380,
    protein: 15.2,
    carbs: 55.4,
    fat: 10.5,
    iron: 3.5,
    sodium: 850,
    price: 150,
    description: 'Himalayan noodle soup, popular in winter.',
    preparation: 'Wheat noodles boiled in a rich meat or vegetable broth with seasonal greens, carrots, and spices.',
    benefits: 'Warming and hydrating. Good source of vegetables and protein depending on the broth.'
  },
  {
    name: 'Alu Tama',
    localName: 'आलु तामा',
    phonetic: 'Aa-loo Taa-maa',
    category: 'Vegetable',
    calories: 120,
    protein: 3.5,
    carbs: 22.1,
    fat: 2.5,
    iron: 1.8,
    price: 100,
    description: 'Classic Nepali curry made with potatoes, bamboo shoots, and black-eyed peas.',
    preparation: 'Fermented bamboo shoots (Tama) cooked with potatoes and soaked black-eyed peas in a sour and spicy broth.',
    benefits: 'Low in calories. Bamboo shoots provide unique phytonutrients and dietary fiber.'
  },
  {
    name: 'Dhikri',
    localName: 'ढिक्री',
    phonetic: 'Dhik-ree',
    category: 'Staple',
    calories: 210,
    protein: 4.2,
    carbs: 45.5,
    fat: 0.5,
    iron: 1.1,
    price: 50,
    description: 'Traditional Tharu steamed rice dough, shaped like sticks or animals.',
    preparation: 'Rice flour kneaded with warm water, shaped, and steamed. Eaten with spicy chutney or lentil soup.',
    benefits: 'Easily digestible, gluten-free, and oil-free staple.'
  },
  {
    name: 'Rikikur',
    localName: 'रिकिकुर',
    phonetic: 'Ri-ki-koor',
    category: 'Snack',
    calories: 280,
    protein: 6.5,
    carbs: 42.3,
    fat: 9.2,
    iron: 2.5,
    price: 100,
    description: 'Sherpa potato pancake.',
    preparation: 'Grated raw potatoes mixed with a little flour and salt, pan-fried in butter or ghee. Served with spicy cheese sauce (Somar).',
    benefits: 'Rich in potassium and complex carbohydrates.'
  },
  {
    name: 'Samay Baji',
    localName: 'समय् बजि',
    phonetic: 'Sa-may Ba-jee',
    category: 'Indigenous',
    calories: 550,
    protein: 25.4,
    carbs: 75.2,
    fat: 15.8,
    iron: 22.5,
    price: 350,
    description: 'Traditional Newari feast set containing beaten rice, roasted meat, black soybeans, ginger, and vegetables.',
    preparation: 'A platter combining Chiura, Chhoila (spiced grilled meat), Bhatmas (roasted soybeans), Bara, and Achar.',
    benefits: 'Highly balanced meal offering diverse textures, high protein, and exceptionally high iron (from Chiura and soybeans).'
  },
  {
    name: 'Bagiya',
    localName: 'बगिया',
    phonetic: 'Ba-gee-yaa',
    category: 'Snack',
    calories: 240,
    protein: 5.5,
    carbs: 48.2,
    fat: 1.2,
    iron: 1.5,
    price: 60,
    description: 'Maithil and Tharu steamed rice flour dumpling, often filled with lentils or jaggery.',
    preparation: 'Rice flour dough stuffed with roasted lentil paste or sweet jaggery, then steamed.',
    benefits: 'Healthy, oil-free snack providing sustained energy.'
  },
  {
    name: 'Pustakari',
    localName: 'पुष्टकारी',
    phonetic: 'Poosh-ta-kaa-ree',
    category: 'Snack',
    calories: 410,
    protein: 8.5,
    carbs: 72.4,
    fat: 10.2,
    iron: 3.2,
    price: 150,
    description: 'Traditional Nepali sweet made from molasses, milk, and nuts.',
    preparation: 'Thickened milk and molasses cooked down with coconut, dates, and spices until hard, then shaped into small balls.',
    benefits: 'Energy-dense, traditionally given to pregnant women and lactating mothers for strength.'
  },
  {
    name: 'Wheat Flatbread',
    localName: 'गहुँको रोटी',
    phonetic: 'Ga-hoon-ko Ro-tee',
    category: 'Staple',
    calories: 297,
    protein: 9.8,
    carbs: 58.6,
    fat: 1.7,
    iron: 3.5,
    price: 25,
    description: 'Whole wheat flatbread, a common staple for dinner or breakfast.',
    preparation: 'Whole wheat flour kneaded with water, rolled into flat circles, and cooked on a hot iron tawa.',
    benefits: 'Good source of complex carbohydrates and dietary fiber.'
  },
  {
    name: 'Tomato Pickle',
    localName: 'गोलभेडाको अचार',
    phonetic: 'Gol-bhay-daa-ko A-chaar',
    category: 'Vegetable',
    calories: 45,
    protein: 1.5,
    carbs: 8.2,
    fat: 1.2,
    iron: 0.8,
    vitaminA: 600,
    price: 30,
    description: 'A tangy and spicy condiment served with almost every Nepali meal.',
    preparation: 'Roasted or boiled tomatoes blended with roasted sesame seeds, garlic, green chilies, and coriander.',
    benefits: 'Rich in Vitamin C and lycopene. Enhances iron absorption from Dal Bhat.'
  },
  {
    name: 'Dried Meat',
    localName: 'सुकुटी',
    phonetic: 'Soo-koo-tee',
    category: 'Protein',
    calories: 320,
    protein: 55.2,
    carbs: 0,
    fat: 10.5,
    iron: 8.5,
    price: 300,
    description: 'Traditional smoke-dried meat (usually buffalo, goat, or wild boar).',
    preparation: 'Strips of meat are marinated in spices and hung over a wood fire to dry. Rehydrated and stir-fried with onions and tomatoes.',
    benefits: 'Extremely concentrated source of high-quality protein and iron.'
  },
  {
    name: 'Yogurt',
    localName: 'दही',
    phonetic: 'Da-hee',
    category: 'Dairy',
    calories: 98,
    protein: 4.3,
    carbs: 5.2,
    fat: 6.5,
    iron: 0.1,
    price: 60,
    description: 'Traditional homemade yogurt, often consumed at the end of a meal or with Chiura.',
    preparation: 'Boiled milk is cooled and inoculated with a starter culture, then left to set in a warm place.',
    benefits: 'Excellent source of probiotics, calcium, and protein. Aids digestion.'
  },
  {
    name: 'Roasted Barley Flour',
    localName: 'सातु',
    phonetic: 'Saa-too',
    category: 'Staple',
    calories: 380,
    protein: 12.5,
    carbs: 75.2,
    fat: 2.5,
    iron: 4.5,
    price: 120,
    description: 'Roasted barley or mixed grain flour, a traditional instant energy food.',
    preparation: 'Mixed with water, milk, or tea to form a paste or drink. Often sweetened with jaggery.',
    benefits: 'Highly digestible, cooling effect on the body, and rich in fiber and protein.'
  },
  {
    name: 'Radish',
    localName: 'मुला',
    phonetic: 'Moo-laa',
    category: 'Vegetable',
    calories: 16,
    protein: 0.7,
    carbs: 3.4,
    fat: 0.1,
    iron: 0.3,
    price: 30,
    description: 'A common winter root vegetable in Nepal, eaten raw or cooked.',
    preparation: 'Eaten raw as a salad, fermented into Sinkhi, or cooked in a curry with potatoes.',
    benefits: 'Very low in calories, high in water content and Vitamin C. Good for digestion.'
  },
  {
    name: 'Bitter Gourd',
    localName: 'करेला',
    phonetic: 'Ka-ray-laa',
    category: 'Vegetable',
    calories: 17,
    protein: 1.0,
    carbs: 3.7,
    fat: 0.2,
    iron: 0.4,
    price: 60,
    description: 'A bitter green vegetable highly valued for its medicinal properties.',
    preparation: 'Sliced and stir-fried with onions and spices, often deep-fried to reduce bitterness.',
    benefits: 'Excellent for blood sugar management and contains compounds that act like insulin.'
  },
  {
    name: 'Pumpkin',
    localName: 'फर्सी',
    phonetic: 'Far-see',
    category: 'Vegetable',
    calories: 26,
    protein: 1.0,
    carbs: 6.5,
    fat: 0.1,
    iron: 0.8,
    vitaminA: 8513,
    price: 40,
    description: 'Sweet, orange-fleshed squash widely grown in Nepali backyards.',
    preparation: 'Cooked into a sweet and savory curry, or the young shoots (Farsi ko Munta) are stir-fried.',
    benefits: 'Exceptionally high in Vitamin A (beta-carotene), great for eye health and immunity.'
  },
  {
    name: 'Local Chicken Meat',
    localName: 'लोकल कुखुराको मासु',
    phonetic: 'Lo-kal Koo-khoo-raa-ko Maa-soo',
    category: 'Protein',
    calories: 239,
    protein: 27.3,
    carbs: 0,
    fat: 13.6,
    iron: 1.3,
    price: 800,
    description: 'Free-range local chicken, prized for its flavor and tough texture.',
    preparation: 'Slow-cooked into a rich, spicy curry (Jhol) with garlic, ginger, and local spices.',
    benefits: 'High-quality lean protein, rich in B-vitamins and zinc. Excellent for muscle repair.'
  },
  {
    name: 'Local River Fish',
    localName: 'लोकल माछा',
    phonetic: 'Lo-kal Maa-chaa',
    category: 'Protein',
    calories: 206,
    protein: 22.1,
    carbs: 0,
    fat: 12.3,
    iron: 1.1,
    price: 500,
    description: 'Freshwater fish from Nepali rivers, often small and eaten whole.',
    preparation: 'Marinated in turmeric and mustard oil, then pan-fried or cooked in a tangy tomato gravy.',
    benefits: 'Great source of Omega-3 fatty acids, high-quality protein, and calcium (if eaten with bones).'
  },
  {
    name: 'Clarified Butter',
    localName: 'घिउ',
    phonetic: 'Ghee-oo',
    category: 'Dairy',
    calories: 900,
    protein: 0,
    carbs: 0,
    fat: 100,
    iron: 0,
    vitaminA: 3000,
    price: 1200,
    description: 'Traditional clarified butter used for cooking and religious ceremonies.',
    preparation: 'Used as a cooking fat, or drizzled over hot Dal Bhat for flavor and nutrition.',
    benefits: 'Rich in fat-soluble vitamins (A, E, K) and butyrate, which supports gut health.'
  },
  {
    name: 'Fiddlehead Fern',
    localName: 'निउरो',
    phonetic: 'Nee-oo-ro',
    category: 'Vegetable',
    calories: 34,
    protein: 4.5,
    carbs: 5.5,
    fat: 0.4,
    iron: 1.3,
    vitaminA: 3617,
    price: 60,
    description: 'Wild edible fern harvested during the monsoon season.',
    preparation: 'Stir-fried with potatoes, garlic, and mustard oil.',
    benefits: 'Rich in antioxidants, Vitamin A, and essential fatty acids. Great for immunity.'
  },
  {
    name: 'Taro Leaves',
    localName: 'कर्कलो',
    phonetic: 'Kar-ka-lo',
    category: 'Vegetable',
    calories: 42,
    protein: 3.0,
    carbs: 6.8,
    fat: 0.7,
    iron: 2.2,
    vitaminA: 4825,
    price: 40,
    description: 'Broad green leaves of the taro plant, popular in the hilly and Terai regions.',
    preparation: 'Cooked into a thick, tangy curry with lemon or tamarind to remove the itchiness.',
    benefits: 'Excellent source of dietary fiber, Vitamin A, and iron. Good for digestion.'
  },
  {
    name: 'Perilla Seeds',
    localName: 'सिलाम',
    phonetic: 'See-laam',
    category: 'Indigenous',
    calories: 534,
    protein: 17.0,
    carbs: 23.0,
    fat: 40.0,
    iron: 5.0,
    price: 200,
    description: 'Aromatic seeds used to make traditional pickles (Achar).',
    preparation: 'Roasted and ground with tomatoes, garlic, and chilies to make a flavorful dip.',
    benefits: 'Exceptionally high in Omega-3 fatty acids, promoting heart and brain health.'
  },
  {
    name: 'Hemp Seeds',
    localName: 'भाङको गेडा',
    phonetic: 'Bhaang-ko Gay-daa',
    category: 'Indigenous',
    calories: 553,
    protein: 31.5,
    carbs: 8.6,
    fat: 48.7,
    iron: 7.9,
    price: 250,
    description: 'Nutritious seeds from the hemp plant, commonly used in pickles.',
    preparation: 'Roasted and ground with spices to make a tangy and nutty Achar.',
    benefits: 'Complete protein source containing all 9 essential amino acids. High in Omega-3 and Omega-6.'
  },
  {
    name: 'Sichuan Pepper',
    localName: 'टिमुर',
    phonetic: 'Tee-moor',
    category: 'Indigenous',
    calories: 295,
    protein: 9.8,
    carbs: 50.6,
    fat: 6.0,
    iron: 4.5,
    price: 400,
    description: 'A unique, tongue-tingling spice native to the Himalayas.',
    preparation: 'Ground into pickles, marinades, or used to flavor meat curries and soups.',
    benefits: 'Known for its digestive and carminative properties. Provides warmth during winter.'
  },
  {
    name: 'Ash Gourd',
    localName: 'कुभिण्डो',
    phonetic: 'Koo-bheen-do',
    category: 'Vegetable',
    calories: 13,
    protein: 0.4,
    carbs: 3.0,
    fat: 0.2,
    iron: 0.4,
    price: 50,
    description: 'A large, mild-flavored melon often used in curries and sweets.',
    preparation: 'Cooked in curries, or candied to make a traditional sweet called Murabba.',
    benefits: 'Highly alkaline and cooling for the body. Very low in calories, good for weight management.'
  },
  {
    name: 'Colocasia Root',
    localName: 'पिँडालु',
    phonetic: 'Peen-daa-loo',
    category: 'Staple',
    calories: 112,
    protein: 1.5,
    carbs: 26.4,
    fat: 0.2,
    iron: 0.5,
    price: 60,
    description: 'Starchy root vegetable widely consumed during the Maghe Sankranti festival.',
    preparation: 'Boiled and eaten with salt and chili, or cooked into a curry.',
    benefits: 'Rich in complex carbohydrates and dietary fiber. Provides sustained energy.'
  },
  {
    name: 'Tree Tomato',
    localName: 'रुख गोलभेडा',
    phonetic: 'Rookh Gol-bhay-daa',
    category: 'Fruit',
    calories: 31,
    protein: 1.5,
    carbs: 7.0,
    fat: 0.3,
    iron: 0.6,
    vitaminA: 600,
    price: 80,
    description: 'Tamarillo, a tangy, egg-shaped fruit grown in the hills.',
    preparation: 'Roasted and mashed to make a sharp, tangy pickle.',
    benefits: 'High in Vitamin C, antioxidants, and potassium. Helps boost immunity.'
  },
  {
    name: 'Potato Yogurt Salad',
    localName: 'चुकौनी',
    phonetic: 'Choo-kau-nee',
    category: 'Vegetable',
    calories: 145,
    protein: 3.5,
    carbs: 18.2,
    fat: 6.5,
    iron: 0.8,
    price: 80,
    description: 'A traditional Palpali dish made with boiled potatoes and yogurt.',
    preparation: 'Boiled potatoes mixed with yogurt, onions, and tempered with mustard oil, fenugreek, and turmeric.',
    benefits: 'Provides a good mix of carbohydrates from potatoes and probiotics from yogurt.'
  },
  {
    name: 'Fermented Leafy Greens',
    localName: 'गुन्द्रुक',
    phonetic: 'Goon-drook',
    category: 'Vegetable',
    calories: 85,
    protein: 3.2,
    carbs: 16.5,
    fat: 0.5,
    iron: 4.5,
    price: 150,
    description: 'Traditional fermented leafy greens, usually mustard or radish leaves.',
    preparation: 'Made into a tangy soup (Jhol) with soybeans, tomatoes, and potatoes.',
    benefits: 'Excellent source of probiotics, fiber, and minerals. Aids digestion.'
  },
  {
    name: 'Fermented Soybeans',
    localName: 'किनेमा',
    phonetic: 'Kee-nay-maa',
    category: 'Protein',
    calories: 180,
    protein: 17.5,
    carbs: 10.2,
    fat: 8.5,
    iron: 3.2,
    price: 200,
    description: 'Sticky, fermented soybeans popular in Eastern Nepal (Limbu culture).',
    preparation: 'Cooked into a strong-flavored curry with tomatoes, onions, and chilies.',
    benefits: 'Rich in easily digestible protein, probiotics, and B-vitamins.'
  },
  {
    name: 'Bamboo Shoots',
    localName: 'तामा',
    phonetic: 'Taa-maa',
    category: 'Vegetable',
    calories: 27,
    protein: 2.6,
    carbs: 5.2,
    fat: 0.3,
    iron: 0.5,
    price: 120,
    description: 'Tender bamboo shoots, often fermented for a sour taste.',
    preparation: 'Cooked in a classic curry (Aloo Tama) with potatoes and black-eyed peas.',
    benefits: 'Low calorie, high fiber, and contains essential minerals like potassium.'
  },
  {
    name: 'Finger Millet',
    localName: 'कोदो',
    phonetic: 'Ko-do',
    category: 'Staple',
    calories: 336,
    protein: 7.3,
    carbs: 72.0,
    fat: 1.3,
    iron: 3.9,
    price: 80,
    description: 'A highly nutritious, drought-resistant grain grown in the hills.',
    preparation: 'Ground into flour to make thick porridge (Dhindo) or flatbreads (Roti).',
    benefits: 'Exceptionally high in calcium, iron, and dietary fiber. Gluten-free.'
  },
  {
    name: 'Buckwheat',
    localName: 'फापर',
    phonetic: 'Phaa-par',
    category: 'Staple',
    calories: 343,
    protein: 13.2,
    carbs: 71.5,
    fat: 3.4,
    iron: 2.2,
    price: 150,
    description: 'A pseudocereal widely consumed in the mountainous regions.',
    preparation: 'Made into flatbreads (Roti), Dhindo, or deep-fried snacks.',
    benefits: 'Rich in complex carbohydrates, high-quality protein, and rutin (good for blood vessels).'
  },
  {
    name: 'Hard Cheese',
    localName: 'छुर्पी',
    phonetic: 'Chhoor-pee',
    category: 'Dairy',
    calories: 350,
    protein: 65.0,
    carbs: 10.0,
    fat: 5.0,
    iron: 1.0,
    price: 1000,
    description: 'Traditional hard cheese made from yak or cow milk.',
    preparation: 'Chewed as a long-lasting snack, or the soft version is cooked in curries.',
    benefits: 'Extremely high in protein and calcium. Good for dental health.'
  },
  {
    name: 'Nepali Hog Plum',
    localName: 'लप्सी',
    phonetic: 'Lap-see',
    category: 'Fruit',
    calories: 45,
    protein: 1.0,
    carbs: 10.5,
    fat: 0.2,
    iron: 0.8,
    price: 100,
    description: 'A highly sour fruit native to Nepal, rich in Vitamin C.',
    preparation: 'Made into sweet and sour candies (Mada), pickles, or tangy curries.',
    benefits: 'Excellent source of Vitamin C and antioxidants. Aids in digestion.'
  }
];
