import React from 'react';
import { 
  Activity, 
  CalendarDays, 
  Search, 
  UtensilsCrossed, 
  Leaf, 
  Wallet, 
  Camera, 
  SunSnow,
  ScanBarcode
} from 'lucide-react';

export const modules = [
  {
    id: 'deficiency',
    title: 'Nutrition Deficiency Profiling',
    description: 'Analyze symptoms for hidden micronutrient gaps (Iron, Vit A, Iodine, Zinc).',
    icon: Activity,
    color: 'bg-rose-300 text-rose-800 dark:bg-rose-900 dark:text-rose-400',
    borderColor: 'border-rose-500/50 dark:border-rose-500/40',
    accentColor: 'text-rose-600 dark:text-rose-400',
    glowColor: 'shadow-rose-500/20',
  },
  {
    id: 'meal-planner',
    title: 'Smart Meal Planner',
    description: 'Personalized weekly meal plans within your budget and local availability.',
    icon: CalendarDays,
    color: 'bg-amber-300 text-amber-800 dark:bg-amber-900 dark:text-amber-400',
    borderColor: 'border-amber-500/50 dark:border-amber-500/40',
    accentColor: 'text-amber-600 dark:text-amber-400',
    glowColor: 'shadow-amber-500/20',
  },
  {
    id: 'food-lookup',
    title: 'Healthy Food Lookup',
    description: 'Search foods for macro breakdown, sodium levels, and healthier alternatives.',
    icon: Search,
    color: 'bg-sky-300 text-sky-800 dark:bg-sky-900 dark:text-sky-400',
    borderColor: 'border-sky-500/50 dark:border-sky-500/40',
    accentColor: 'text-sky-600 dark:text-sky-400',
    glowColor: 'shadow-sky-500/20',
  },
  {
    id: 'absorption',
    title: 'Absorption Advisor',
    description: 'Analyze meals for nutrient inhibitors and get simple fixes (e.g. lemon + spinach).',
    icon: UtensilsCrossed,
    color: 'bg-fuchsia-300 text-fuchsia-800 dark:bg-fuchsia-900 dark:text-fuchsia-400',
    borderColor: 'border-fuchsia-500/50 dark:border-fuchsia-500/40',
    accentColor: 'text-fuchsia-600 dark:text-fuchsia-400',
    glowColor: 'shadow-fuchsia-500/20',
  },
  {
    id: 'superfoods',
    title: 'Hidden Superfoods',
    description: 'Rediscover indigenous Nepali foods like sisnu and kinema for better health.',
    icon: Leaf,
    color: 'bg-violet-300 text-violet-800 dark:bg-violet-900 dark:text-violet-400',
    borderColor: 'border-violet-500/50 dark:border-violet-500/40',
    accentColor: 'text-violet-600 dark:text-violet-400',
    glowColor: 'shadow-violet-500/20',
  },
  {
    id: 'budget-meals',
    title: 'Healthy Budget Meals',
    description: 'Find quantified alternatives showing better health value per rupee spent.',
    icon: Wallet,
    color: 'bg-orange-300 text-orange-800 dark:bg-orange-900 dark:text-orange-400',
    borderColor: 'border-orange-500/50 dark:border-orange-500/40',
    accentColor: 'text-orange-600 dark:text-orange-400',
    glowColor: 'shadow-orange-500/20',
  },
  {
    id: 'plate-recognition',
    title: 'Plate Recognition',
    description: 'Snap your plate to identify foods, estimate portions, and calculate macros.',
    icon: Camera,
    color: 'bg-cyan-300 text-cyan-800 dark:bg-cyan-900 dark:text-cyan-400',
    borderColor: 'border-cyan-500/50 dark:border-cyan-500/40',
    accentColor: 'text-cyan-600 dark:text-cyan-400',
    glowColor: 'shadow-cyan-500/20',
  },
  {
    id: 'seasonal',
    title: 'Seasonal Calendar',
    description: 'Track seasonal foods and adjust diet plans to predict the hungry season.',
    icon: SunSnow,
    color: 'bg-indigo-300 text-indigo-800 dark:bg-indigo-900 dark:text-indigo-400',
    borderColor: 'border-indigo-500/50 dark:border-indigo-500/40',
    accentColor: 'text-indigo-600 dark:text-indigo-400',
    glowColor: 'shadow-indigo-500/20',
  },
  {
    id: 'recipes',
    title: 'Nepali Recipes',
    description: 'Enter ingredients from your kitchen to get healthy, traditional Nepali recipe suggestions.',
    icon: Leaf,
    color: 'bg-teal-300 text-teal-800 dark:bg-teal-900 dark:text-teal-400',
    borderColor: 'border-teal-500/50 dark:border-teal-500/40',
    accentColor: 'text-teal-600 dark:text-teal-400',
    glowColor: 'shadow-teal-500/20',
  },
  {
    id: 'nutri-score',
    title: 'Poshan Score',
    description: 'Scan a barcode or snap a picture of a nutrition label to get its Poshan Score (A-E) and healthier alternatives.',
    icon: ScanBarcode,
    color: 'bg-fuchsia-300 text-fuchsia-800 dark:bg-fuchsia-900 dark:text-fuchsia-400',
    borderColor: 'border-fuchsia-500/50 dark:border-fuchsia-500/40',
    accentColor: 'text-fuchsia-600 dark:text-fuchsia-400',
    glowColor: 'shadow-fuchsia-500/20',
  },
];
